github: [acctiveoffice]
patreon: acctiveoffice
open_collective: acctiveoffice
ko_fi: acctiveoffice
tidelift: acctiveoffice
community_bridge: acctiveoffice
liberapay: acctiveoffice
issuehunt: acctiveoffice
otechie: acctiveoffice
custom: ['https://example.com']
